name = "adiya-push"
main = "worker.js"
compatibility_date = "2026-01-01"

[[kv_namespaces]]
binding = "SUBS"
id = "bf25129dd2804a238a464f14de12bdf1"

[triggers]
crons = ["*/5 * * * *"]

[vars]
VAPID_SUBJECT = "mailto:everest800@gmail.com"
VAPID_PUBLIC_KEY = "BFz7Al3L0lkhYX9oh7m-YXTVdi9BbEyye5qg_hgGGx5sI2EtHOnZw2CLeOWqvHX6-4Lk4b9Gh2EWlkyps0b2cug"
